import { Video } from "@/types/video";

export const mockVideos: Video[] = [
  {
    id: "1",
    title: "Learn English with Friends",
    subTitle: "Funny moments for learning English with friends Funny moments for learning English with friends Funny moments for learning English with friends Funny moments for learning English with friends ",
    channelName: "English with TV Series",
    videoId: "uiUCIz-3CWM",
    thumbnailURL: "https://i.ytimg.com/vi/uiUCIz-3CWM/hqdefault.jpg",
    duration: "29:50",
    views: 1234,
    publishedAt: "8 hours ago",
  },
  {
    id: "2",
    title: "Everyday English Conversation",
    subTitle: "Practice speaking with real situations",
    channelName: "English Addict",
    videoId: "uiUCIz-3CWM",
    thumbnailURL: "https://i.ytimg.com/vi/uiUCIz-3CWM/hqdefault.jpg",
    duration: "12:34",
    views: 567,
    publishedAt: "1 day ago",
  },
  {
    id: "3",
    title: "Shadowing: Improve Your Pronunciation",
    subTitle: "Shadow native speakers for fluency",
    channelName: "FluentU English",
    videoId: "uiUCIz-3CWM",
    thumbnailURL: "https://i.ytimg.com/vi/uiUCIz-3CWM/hqdefault.jpg",
    duration: "10:01",
    views: 999,
    publishedAt: "2 days ago",
  },
  {
    id: "4",
    title: "English Listening Practice",
    subTitle: "Listen and repeat for better understanding",
    channelName: "Learn English Lab",
    videoId: "uiUCIz-3CWM",
    thumbnailURL: "https://i.ytimg.com/vi/uiUCIz-3CWM/hqdefault.jpg",
    duration: "15:45",
    views: 321,
    publishedAt: "3 days ago",
  },
  {
    id: "5",
    title: "English Shadowing for Beginners",
    subTitle: "Start shadowing with simple sentences",
    channelName: "Speak English With Vanessa",
    videoId: "uiUCIz-3CWM",
    thumbnailURL: "https://i.ytimg.com/vi/uiUCIz-3CWM/hqdefault.jpg",
    duration: "08:22",
    views: 88,
    publishedAt: "5 days ago",
  },
];
